/** @type {Record<string, import('./skinTypes.js').SkinDefinition>} */
export const SKIN_DEFINITIONS = Object.freeze({
    classic: {
        label: 'Classique',
        hint: 'Toujours disponible',
        family: 'classic',
        palette: {
            body: 0xFFCC00,
            bodyHi: 0xFFEE88,
            wing: 0xFFAA00,
            beak: 0xFF8800,
            beakDark: 0xCC5500,
        },
        unlock: { type: 'always' },
    },
    lavande: {
        label: 'Lavande',
        hint: 'Meilleur score ≥ 5',
        family: 'classic',
        palette: {
            body: 0xB39DDB,
            bodyHi: 0xE1BEE7,
            wing: 0x9575CD,
            beak: 0xFF8A65,
            beakDark: 0xE64A19,
        },
        unlock: { type: 'scoreAny', min: 5 },
    },
    ruby: {
        label: 'Rubis',
        hint: 'Meilleur score ≥ 10',
        family: 'classic',
        palette: {
            body: 0xE53935,
            bodyHi: 0xFF8A80,
            wing: 0xC62828,
            beak: 0xFF6F00,
            beakDark: 0xE65100,
        },
        unlock: { type: 'scoreAny', min: 10 },
    },
    ambre: {
        label: 'Ambre',
        hint: 'Meilleur score ≥ 12',
        family: 'classic',
        palette: {
            body: 0xFFB300,
            bodyHi: 0xFFE082,
            wing: 0xFF8F00,
            beak: 0xFF6D00,
            beakDark: 0xE65100,
        },
        unlock: { type: 'scoreAny', min: 12 },
    },
    ocean: {
        label: 'Océan',
        hint: 'Meilleur score ≥ 20',
        family: 'classic',
        palette: {
            body: 0x29B6F6,
            bodyHi: 0x81D4FA,
            wing: 0x0288D1,
            beak: 0xFF8F00,
            beakDark: 0xEF6C00,
        },
        unlock: { type: 'scoreAny', min: 20 },
    },
    corail: {
        label: 'Corail',
        hint: 'Meilleur score ≥ 25',
        family: 'classic',
        palette: {
            body: 0xFF7043,
            bodyHi: 0xFFAB91,
            wing: 0xF4511E,
            beak: 0xFFD54F,
            beakDark: 0xFFA000,
        },
        unlock: { type: 'scoreAny', min: 25 },
    },
    forest: {
        label: 'Forêt',
        hint: 'Meilleur score hardcore ≥ 5',
        family: 'classic',
        palette: {
            body: 0x66BB6A,
            bodyHi: 0xA5D6A7,
            wing: 0x388E3C,
            beak: 0xFFA726,
            beakDark: 0xF57C00,
        },
        unlock: { type: 'hardcore', min: 5 },
    },
    minuit: {
        label: 'Minuit',
        hint: 'Meilleur score ≥ 15',
        family: 'classic',
        palette: {
            body: 0x3949AB,
            bodyHi: 0x7986CB,
            wing: 0x283593,
            beak: 0xB0BEC5,
            beakDark: 0x78909C,
        },
        unlock: { type: 'scoreAny', min: 15 },
    },
    armure: {
        label: 'Chevalier',
        hint: 'Meilleur score hardcore ≥ 15',
        family: 'special',
        palette: {
            body: 0x78909C,
            bodyHi: 0xB0BEC5,
            wing: 0x546E7A,
            beak: 0xCFD8DC,
            beakDark: 0x90A4AE,
            helmet: 0x455A64,
            helmetHi: 0x607D8B,
            plume: 0xC62828,
        },
        accessoryKey: 'armure',
        unlock: { type: 'hardcore', min: 15 },
    },
    mushu: {
        label: 'Mushu',
        hint: 'Score ≥ 15 dans les 3 difficultés',
        family: 'special',
        palette: {
            body: 0xE64A19,
            bodyHi: 0xFFCA28,
            wing: 0xBF360C,
            beak: 0xFFD54F,
            beakDark: 0xFFA000,
            horn: 0xFFD54F,
            ridge: 0xFFCA28,
            whisker: 0xFFECB3,
        },
        accessoryKey: 'mushu',
        unlock: { type: 'allDifficulties', min: 15 },
    },
    phoenix: {
        label: 'Phénix',
        hint: 'Meilleur score hardcore ≥ 20',
        family: 'special',
        palette: {
            body: 0xFF5722,
            bodyHi: 0xFFAB91,
            wing: 0xE64A19,
            beak: 0xFFD54F,
            beakDark: 0xFF8F00,
            flame: 0xFFEB3B,
            ember: 0xFF6F00,
        },
        accessoryKey: 'phoenix',
        unlock: { type: 'hardcore', min: 20 },
    },
    fantome: {
        label: 'Fantôme',
        hint: 'Meilleur score ≥ 30',
        family: 'special',
        palette: {
            body: 0xE0F7FA,
            bodyHi: 0xFFFFFF,
            wing: 0xB2EBF2,
            beak: 0xE1F5FE,
            beakDark: 0xB3E5FC,
            glow: 0x18FFFF,
            wisp: 0xE0F7FA,
        },
        accessoryKey: 'fantome',
        unlock: { type: 'scoreAny', min: 30 },
    },
    glace: {
        label: 'Glace',
        hint: '3 défis du jour réussis',
        family: 'special',
        palette: {
            body: 0xB3E5FC,
            bodyHi: 0xE1F5FE,
            wing: 0x4FC3F7,
            beak: 0xFFE082,
            beakDark: 0xFFB300,
            crystal: 0xFFFFFF,
            shine: 0xE0F7FA,
        },
        accessoryKey: 'glace',
        unlock: { type: 'dailyCompletions', min: 3 },
    },
    tempete: {
        label: 'Tempête',
        hint: '10 pts en entraînement',
        family: 'special',
        palette: {
            body: 0x607D8B,
            bodyHi: 0x90A4AE,
            wing: 0x455A64,
            beak: 0xFFD54F,
            beakDark: 0xFFA000,
            cloud: 0xCFD8DC,
            bolt: 0xFFEB3B,
        },
        accessoryKey: 'tempete',
        unlock: { type: 'training', min: 10 },
    },
    cosmos: {
        label: 'Cosmos',
        hint: 'Meilleur score hardcore ≥ 28',
        family: 'special',
        palette: {
            body: 0x311B92,
            bodyHi: 0x5E35B1,
            wing: 0x4527A0,
            beak: 0xCE93D8,
            beakDark: 0x8E24AA,
            star: 0xFFFFFF,
            ring: 0xB388FF,
        },
        accessoryKey: 'cosmos',
        unlock: { type: 'hardcore', min: 28 },
    },
    neon: {
        label: 'Néon',
        hint: 'Collection complète (15 skins)',
        family: 'special',
        palette: {
            body: 0x1A1A2E,
            bodyHi: 0x3D2C5C,
            wing: 0x00E5FF,
            beak: 0xFF2BD6,
            beakDark: 0xC2185B,
            visor: 0xFF2BD6,
            trim: 0x00E5FF,
        },
        accessoryKey: 'neon',
        unlock: { type: 'neonCollection' },
    },
});
